### PR TITLE
Develop Attractions API

### PR DESCRIPTION
**Pull request by joanncheng**
Discord Name: Joann

API Test URL: 
http://52.37.246.45:3000/api/attractions?page=1
http://52.37.246.45:3000/api/attractions?page=0&keyword=公園
http://52.37.246.45:3000/api/attraction/13

### CODE REVIEW

**Review by cwpeng — APPROVED** [review]
Well Done. :)

**Comment by cwpeng** [comment]
Suggestion:

If you want to get count of rows in a table, just use `SELECT count(*) FROM TABLE_NAME`. It's the best practice and optimized by MySQL server.

**Comment by joanncheng** [comment]
> Suggestion:
> 
> If you want to get count of rows in a table, just use `SELECT count(*) FROM TABLE_NAME`. It's the best practice and optimized by MySQL server.

Thank you for your suggestion~
I had tried this method, but it did not work, because it returned None.
Therefore I used cursor.rowcount instead.

And I've just found out the documentation ([PEP249](https://www.python.org/dev/peps/pep-0249/#major-changes-from-version-1-0-to-version-2-0)) mentions :

> The definition of the [.execute()](https://www.python.org/dev/peps/pep-0249/#id16) return value changed. Previously, the return value was based on the SQL statement type (which was hard to implement right) — it is undefined now; use the more flexible [.rowcount](https://www.python.org/dev/peps/pep-0249/#rowcount) attribute instead. Modules are free to return the old style return values, but these are no longer mandated by the specification and should be considered database interface dependent.

**Comment by cwpeng** [comment]
What you found talks about another issue different from what I say.

I'm very sure that you should use `SELECT count(*) FROM TABLE_NAME` to get row count efficiently. Try to find way, it's easy and straightforward actually.

**Comment by joanncheng** [comment]
> What you found talks about another issue different from what I say.
> 
> I'm very sure that you should use `SELECT count(*) FROM TABLE_NAME` to get row count efficiently. Try to find way, it's easy and straightforward actually.

I'm so sorry I didn't read the content you wrote clearly.(＞人＜；)
I'll use `SELECT count(*) FROM TABLE_NAME` to get row count instead.

Thank you SO much!

**Pull request merged**
